# Generated by Django 5.1.2 on 2024-10-15 12:10

import datetime
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0001_initial'),
        ('projects', '0002_alter_project_deadline'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='project',
            options={'ordering': ['deadline', 'title']},
        ),
        migrations.AlterModelOptions(
            name='projectmember',
            options={'ordering': [models.Case(models.When(role='ADMIN', then=0), models.When(role='MEMBER', then=1), default=2, output_field=models.IntegerField())]},
        ),
        migrations.AlterField(
            model_name='project',
            name='deadline',
            field=models.DateField(validators=[django.core.validators.MinValueValidator(datetime.date(2024, 10, 15), 'A data de término deve ser maior que a data atual.')]),
        ),
        migrations.AlterField(
            model_name='project',
            name='documents',
            field=models.ManyToManyField(blank=True, related_name='projects', to='documents.document'),
        ),
    ]
