# Generated by Django 5.1.2 on 2024-10-09 16:51

import datetime
import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('projects', '0002_alter_project_deadline'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=300)),
                ('description', models.TextField(blank=True, null=True)),
                ('priority', models.CharField(choices=[('HIGH', 'Alta'), ('MEDIUM', 'Média'), ('LOW', 'Baixa')], max_length=50)),
                ('status', models.CharField(choices=[('TO_DO', 'A fazer'), ('DEVELOPING', 'Desenvolvendo'), ('PAUSED', 'Pausado'), ('DONE', 'Finalizado')], max_length=50)),
                ('deadline', models.DateField(validators=[django.core.validators.MinValueValidator(datetime.date(2024, 10, 9), 'A data de término deve ser maior que a data atual.')])),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to='projects.project')),
                ('responsible_people', models.ManyToManyField(related_name='tasks', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-deadline', 'title'],
            },
        ),
    ]
