# Generated by Django 5.1.2 on 2024-10-17 15:01

import datetime
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0002_alter_task_options_alter_task_deadline'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='task',
            options={'ordering': [models.Case(models.When(status='DONE', then=models.Value(1)), models.When(status='TO_DO', then=models.Value(0)), models.When(status='PAUSED', then=models.Value(0)), models.When(status='DEVELOPING', then=models.Value(0)), output_field=models.IntegerField()), 'deadline', 'title']},
        ),
        migrations.AlterField(
            model_name='task',
            name='deadline',
            field=models.DateField(validators=[django.core.validators.MinValueValidator(datetime.date(2024, 10, 17), 'A data de término deve ser maior que a data atual.')]),
        ),
    ]
